import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Timer from "../components/Timer/Timer";

function Home() {
  const time = new Date();
  time.setSeconds(time.getSeconds() + 10);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Timer expiryTimestamp={time} />
    </div>
  );
}

export default Home;
